version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    env_file:
<<<<<<< HEAD
      - .env
=======
      - docker.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres:postgres
  #   container_name: nestjs-pgadmin
  #   ports:
  #     - '5050:80'
  #   volumes:
  #     - ./pgadmin:/root/.pgadmin
  #   env_file:
  #     - docker.env
  #   networks:
  #     - postgres

  rest7:
    container_name: rest7
    links:
      - postgres:postgres
>>>>>>> 7733f267cac06c7954a764294ad21941c3daa190
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${PORT}
    networks:
      - custom-network
    volumes:
      - ./logger:/app/logger
      - ./src:/app/src
      - ./node_modules:/app/node_modules

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - PGDATA:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}
    networks:
      - custom-network
    volumes:
      - ./pg_data:${PGDATA}

networks:
  custom-network:
    name: custom-network
    driver: bridge

volumes:
  pgdata:
    driver: local
