version: '3.9'

services:
  postgres:
    image: postgres
    container_name: rest-db-postgres
    restart: always
    env_file:
      - docker.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  rest-api:
    image: rest-api
    container_name: rest-api
    links:
      - postgres:postgres
    depends_on:
      - postgres
      - pgadmin
    env_file:
      - docker.env
    build: .
    ports:
      - '4000:4000'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
#Voolumes
volumes:
  dbdata:
    driver: local
